version: "3"
services:
  php:
    build: .
    command: "php ./index.php"
    networks:
      - learn-docker-network

  db:
    image: postgres:13.12-alpine
    restart: always
    env_file:
      - ".env"
    volumes:
      - postgresdb_data:/var/lib/postgresql/data
    networks:
      - learn-docker-network

  adminer:
    image: adminer
    restart: always
    networks:
      - learn-docker-network

  nginx:
    image: nginx:stable-alpine
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf.prod:/etc/nginx/conf.d/nginx.conf
    depends_on:
      - php
      - db
      - adminer
    networks:
      - learn-docker-network

volumes:
  postgresdb_data:

networks:
  learn-docker-network:
    driver: bridge

