version: "3"
services:
  php:
    build: ./images/php
    volumes:
      - ./www:/var/www
    networks:
      - learn-docker-network

  db:
    image: postgres:13.12-alpine
    restart: always
    env_file:
      - ".env"
    volumes:
      - postgresdb_data:/var/lib/postgresql/data
    networks:
      - learn-docker-network

  nginx:
    image: nginx:stable-alpine
    ports:
      - 80:80
    volumes:
      - ./www:/var/www
      - ./nginx/nginx.conf.prod:/etc/nginx/conf.d/nginx.conf
    depends_on:
      - php
      - db
    networks:
      - learn-docker-network

volumes:
  postgresdb_data:


networks:
  learn-docker-network:
    driver: bridge
